[project]
name = "aris-inventory-labeling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.2",
    "qrcode>=8.2",
    "reportlab>=4.4.3",
]
